// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANxbnIxpdhZDZQyBndy5Kp5fjzb7j-dv0',
    appId: '1:87644550019:web:cbef744f750dc9db6bbcb6',
    messagingSenderId: '87644550019',
    projectId: 'hostelmangement-16906',
    authDomain: 'hostelmangement-16906.firebaseapp.com',
    storageBucket: 'hostelmangement-16906.appspot.com',
    measurementId: 'G-ZWM5RC0SJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD1WueSA8YJVRvMBpcCnBAnTn55cf5KvI',
    appId: '1:87644550019:android:b1dbe64e887a92066bbcb6',
    messagingSenderId: '87644550019',
    projectId: 'hostelmangement-16906',
    storageBucket: 'hostelmangement-16906.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_FL1qnS2DOQOKl8d7dX0Itf062G5r1p8',
    appId: '1:87644550019:ios:a4fdedd29b7368b46bbcb6',
    messagingSenderId: '87644550019',
    projectId: 'hostelmangement-16906',
    storageBucket: 'hostelmangement-16906.appspot.com',
    iosBundleId: 'com.example.hostelMangement',
  );
}
